config/routes.rb
Rails.application.routes.draw do
  # Invitation routes
  # # resources :invitations, only: [:new, :create]
  # get 'accept_invitation', to: 'invitations#accept'
  # post 'complete_registration', to: 'invitations#complete_registration'
  # Root and authentication
  root to: 'home#welcome'

  # Scoped routes based on company name
  scope '/:company_name' do
    # Move set_password and update_password outside company scope

    # Invitation routes
    resources :invitations, only: [:new, :create]
    get 'accept_invitation', to: 'invitations#accept', as: 'accept_invitation'
    get 'dashboard', to: 'dashboards#show', as: :company_dashboard
    resources :companies
    # Keg inventory routes
    get 'keg_inventory', to: 'keg_inventory#index', as: :keg_inventory
    get 'keg_inventory/:recipe_id', to: 'keg_inventory#show', as: :keg_inventory_show
    post 'share_kegs', to: 'keg_inventory#share', as: :share_kegs
    resources :brews do
      member do
        post :empty_vessel
      end
      # Adding routes for viewing all logs and specific log actions
      post :transfer_kegs, on: :member
      resources :mash_logs, only: [:index, :new, :create, :edit, :update]
      resources :boil_logs, only: [:index, :new, :create, :edit, :update] do
        collection do
          get :new_preboil
          post :create_preboil
          get :new_postboil
          post :create_postboil
        end
      end
      resources :addition_logs, only: [:index, :new, :create, :edit, :update]
      resources :yeast_and_knockout_logs, only: [:index, :new, :create, :edit, :update]
      resources :fermentation_logs, only: [:index, :new, :create]
    end

    resources :recipes
    resources :vessels
    resources :ingredients
    resources :kegs
    post 'switch_company', to: 'companies#switch_company', as: :switch_company
  end

  # Company routes
  resources :companies
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :company

  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients

  # Categories Constant for ingredients
  CATEGORIES = ['Malts (Grains)', 'Hops', 'Yeast', 'Puree', 'Other'].freeze
  # Unit Types Constant for Ingredients
  UNIT_TYPES = ['Bag', 'Barrel', 'Container', 'Packet', 'Box', 'Other'].freeze
  # Validations
  validates :name, presence: true
  validates :category, inclusion: { in: CATEGORIES, allow_nil: true }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }

  # Scopes
  scope :sorted_by_category, -> {
    order(Arel.sql("CASE
                      WHEN category = 'Malts (Grains)' THEN 1
                      WHEN category = 'Hops' THEN 2
                      WHEN category = 'Yeast' THEN 3
                      WHEN category = 'Puree' THEN 4
                      WHEN category = 'Other' THEN 5
                      ELSE 6
                    END, category ASC"))
  }
  # Calculate total weight dynamically
  def calculate_total_weight
    (amount || 0) * (weight_per_unit || 0)
  end

  def display_name
    brand.present? ? "#{brand} #{name} (#{category})" : "#{name} (#{category})"
  end

  private

  def update_total_weight
    self.total_weight = (amount || 0) * (weight_per_unit || 0)
    save if changed? # Ensures it saves only if there are changes
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_company
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def index
    @ingredients = @company.ingredients
    @ingredients_by_category = @ingredients.group_by(&:category).sort_by do |category, _|
      Ingredient::CATEGORIES.index(category) || Ingredient::CATEGORIES.length
    end
  end

  def new
    @ingredient = @company.ingredients.build
  end

  def create
    @ingredient = @company.ingredients.build(ingredient_params)
    @ingredient.total_weight = @ingredient.calculate_total_weight
    if @ingredient.save
      redirect_to ingredients_path(company_name: @company.slug), notice: 'Ingredient was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @ingredient.update(ingredient_params.merge(total_weight: @ingredient.calculate_total_weight))
      redirect_to ingredients_path(company_name: @company.slug), notice: 'Ingredient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path(company_name: @company.slug), notice: 'Ingredient was successfully deleted.'
  end

  private

  def set_ingredient
    @ingredient = @company.ingredients.find(params[:id])
  end

  def set_company
    @company = Company.friendly.find(params[:company_name])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :category, :amount, :type_of_unit, :weight_per_unit, :total_weight, :unit_of_measurement, :brand)
  end
end

app/views/ingredients/_form.html.haml
= form_with model: @ingredient, url: @ingredient.persisted? ? ingredient_path(company_name: @company.slug, id: @ingredient) : ingredients_path(company_name: @company.slug), local: true, class: "needs-validation" do |f|

  - if @ingredient.errors.any?
    .alert.alert-danger
      %h4.alert-heading= "There were errors with your submission:"
      %ul
        - @ingredient.errors.full_messages.each do |message|
          %li= message

  .mb-3
    = f.label :name, class: "form-label"
    = f.text_field :name, class: "form-control", required: true

  .mb-3
    = f.label :category, class: "form-label"
    = f.select :category, Ingredient::CATEGORIES, { include_blank: "Select Category" }, class: "form-select", required: true

  .mb-3
    = f.label :amount, class: "form-label"
    = f.number_field :amount, step: 0.01, class: "form-control", required: true

  .mb-3
    = f.label :type_of_unit, class: "form-label"
    = f.select :type_of_unit, Ingredient::UNIT_TYPES, { include_blank: "Select Unit Type" }, class: "form-select", required: true

  .mb-3
    = f.label :weight_per_unit, class: "form-label"
    = f.number_field :weight_per_unit, step: 0.01, class: "form-control", required: true

  .mb-3
    = f.label :total_weight, class: "form-label"
    = f.number_field :total_weight, step: 0.01, class: "form-control", disabled: true, value: @ingredient.calculate_total_weight

  .mb-3
    = f.label :brand, class: "form-label"
    = f.text_field :brand, class: "form-control"

  .d-flex.justify-content-end.mt-4
    = f.submit "Save", class: "btn btn-primary"

app/views/ingredients/_ingredients_table.html.haml
/ ** Responsive Ingredient Table **
.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Name
        %th Brand
        %th Amount
        %th Type
        %th Weight/Unit
        %th Total Weight
        %th.text-center Actions
    %tbody
      - if ingredients.any?
        - ingredients.each do |ingredient|
          %tr
            %td= ingredient.name
            %td= ingredient.brand.presence || 'N/A'
            %td= ingredient.amount
            %td= ingredient.type_of_unit
            %td= ingredient.weight_per_unit
            %td= ingredient.total_weight
            %td.text-center
              .d-flex.justify-content-center.gap-2
                = link_to ingredient_path(@company, ingredient), class: "text-primary text-decoration-none d-flex align-items-center gap-1" do
                  %i.fas.fa-eye
                  %span.d-none.d-md-inline View
                = link_to edit_ingredient_path(@company, ingredient), class: "text-secondary text-decoration-none d-flex align-items-center gap-1" do
                  %i.fas.fa-edit
                  %span.d-none.d-md-inline Edit
                = link_to ingredient_path(@company, ingredient), method: :delete, data: { confirm: "Are you sure?" }, class: "text-danger text-decoration-none d-flex align-items-center gap-1" do
                  %i.fas.fa-trash-alt
                  %span.d-none.d-md-inline Delete
      - else
        %tr
          %td.colspan-7.text-center.text-muted No ingredients found in this category.

app/views/ingredients/edit.html.haml
%h1 Edit Ingredient
= render 'form', ingredient: @ingredient, company: @company

app/views/ingredients/index.html.haml
%h1.text-center.mb-4 Ingredients Inventory

.row.mb-3
  .col-md-6
    %h2.fs-4.text-muted Inventory Overview
  .col-md-6.text-end
    = link_to new_ingredient_path(@company), class: "btn btn-success" do
      %i.bi.bi-plus-circle
      Add Ingredient

%ul.nav.nav-tabs.mb-4{"role" => "tablist"}
  %li.nav-item
    %a.nav-link.active{"data-bs-toggle" => "tab", href: "#maltsTab", "role" => "tab"} Malts (Grains)
  %li.nav-item
    %a.nav-link{"data-bs-toggle" => "tab", href: "#hopsTab", "role" => "tab"} Hops
  %li.nav-item
    %a.nav-link{"data-bs-toggle" => "tab", href: "#yeastTab", "role" => "tab"} Yeast
  %li.nav-item
    %a.nav-link{"data-bs-toggle" => "tab", href: "#pureeTab", "role" => "tab"} Puree
  %li.nav-item
    %a.nav-link{"data-bs-toggle" => "tab", href: "#otherTab", "role" => "tab"} Other

.tab-content
  #maltsTab.tab-pane.fade.show.active{"role" => "tabpanel"}
    = render partial: 'ingredients_table', locals: { ingredients: @ingredients.where(category: 'Malts (Grains)') }

  #hopsTab.tab-pane.fade{"role" => "tabpanel"}
    = render partial: 'ingredients_table', locals: { ingredients: @ingredients.where(category: 'Hops') }

  #yeastTab.tab-pane.fade{"role" => "tabpanel"}
    = render partial: 'ingredients_table', locals: { ingredients: @ingredients.where(category: 'Yeast') }

  #pureeTab.tab-pane.fade{"role" => "tabpanel"}
    = render partial: 'ingredients_table', locals: { ingredients: @ingredients.where(category: 'Puree') }

  #otherTab.tab-pane.fade{"role" => "tabpanel"}
    = render partial: 'ingredients_table', locals: { ingredients: @ingredients.where(category: 'Other') }

app/views/ingredients/new.html.haml
%h1 New Ingredient
= render 'form', ingredient: @ingredient, company: @company

app/views/ingredients/show.html.haml
%h1.text-center.mb-4.text-primary= @ingredient.name

.card.shadow-sm
  .card-body
    %h5.card-title.text-secondary Ingredient Details
    %hr
    .row.g-3
      .col-md-6
        %p.mb-1
          %strong Category: 
          = @ingredient.category
        %p.mb-1
          %strong Brand: 
          = @ingredient.brand.presence || 'N/A'
        %p.mb-1
          %strong Amount: 
          = @ingredient.amount
      .col-md-6
        %p.mb-1
          %strong Type of Unit: 
          = @ingredient.type_of_unit
        %p.mb-1
          %strong Weight per Unit: 
          = @ingredient.weight_per_unit
        %p.mb-1
          %strong Total Weight: 
          = @ingredient.total_weight

  .card-footer.d-flex.justify-content-end.gap-2
    = link_to edit_ingredient_path(@company, @ingredient), class: "text-secondary text-decoration-none d-flex align-items-center gap-1" do
      %i.fas.fa-edit
      Edit
    = link_to ingredients_path(@company), class: "text-secondary text-decoration-none d-flex align-items-center gap-1" do
      %i.fas.fa-arrow-left
      Back