config/routes.rb
Rails.application.routes.draw do
  # Invitation routes
  # # resources :invitations, only: [:new, :create]
  # get 'accept_invitation', to: 'invitations#accept'
  # post 'complete_registration', to: 'invitations#complete_registration'
  # Root and authentication
  root to: 'home#welcome'

  # Scoped routes based on company name
  scope '/:company_name' do
    # Move set_password and update_password outside company scope

    # Invitation routes
    resources :invitations, only: [:new, :create]
    get 'accept_invitation', to: 'invitations#accept', as: 'accept_invitation'
    get 'dashboard', to: 'dashboards#show', as: :company_dashboard
    resources :companies
    # Keg inventory routes
    get 'keg_inventory', to: 'keg_inventory#index', as: :keg_inventory
    get 'keg_inventory/:recipe_id', to: 'keg_inventory#show', as: :keg_inventory_show
    post 'share_kegs', to: 'keg_inventory#share', as: :share_kegs
    resources :brews do
      member do
        post :empty_vessel
      end
      # Adding routes for viewing all logs and specific log actions
      post :transfer_kegs, on: :member
      resources :mash_logs, only: [:index, :new, :create, :edit, :update]
      resources :boil_logs, only: [:index, :new, :create, :edit, :update] do
        collection do
          get :new_preboil
          post :create_preboil
          get :new_postboil
          post :create_postboil
        end
      end
      resources :addition_logs, only: [:index, :new, :create, :edit, :update]
      resources :yeast_and_knockout_logs, only: [:index, :new, :create, :edit, :update]
      resources :fermentation_logs, only: [:index, :new, :create]
    end

    resources :recipes
    resources :vessels
    resources :ingredients
    resources :kegs
    post 'switch_company', to: 'companies#switch_company', as: :switch_company
  end

  # Company routes
  resources :companies
end

app/models/vessel.rb
class Vessel < ApplicationRecord
  belongs_to :company
  validates :name, presence: true
  validates :size_bbl, numericality: { greater_than: 0 }
  has_many :brews, dependent: :destroy
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_company
  before_action :set_vessel, only: [:show, :edit, :update, :destroy]

  # GET /:company_name/vessels
  def index
    @vessels = @company.vessels

    respond_to do |format|
      format.html  # Render Haml view
      format.json { render json: @vessels }  # Return JSON response
    end
  end

  # GET /:company_name/vessels/:id
  def show
    respond_to do |format|
      format.html  # Render Haml view
      format.json { render json: @vessel }  # Return JSON response
    end
  end

  # GET /:company_name/vessels/new
  def new
    @vessel = @company.vessels.build
  end

  # POST /:company_name/vessels
  def create
    @vessel = @company.vessels.build(vessel_params)

    respond_to do |format|
      if @vessel.save
        format.html { redirect_to vessels_path(company_name: @company.slug), notice: 'Vessel was successfully created.' }
        format.json { render json: @vessel, status: :created }
      else
        format.html { render :new }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /:company_name/vessels/:id/edit
  def edit; end

  # PATCH/PUT /:company_name/vessels/:id
  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        format.html { redirect_to vessels_path(company_name: @company.slug), notice: 'Vessel was successfully updated.' }
        format.json { render json: @vessel }
      else
        format.html { render :edit }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /:company_name/vessels/:id
  def destroy
    @vessel.destroy

    respond_to do |format|
      format.html { redirect_to company_vessels_path(company_name: @company.slug), notice: 'Vessel was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_company
    @company = Company.find_by!(slug: params[:company_name])
  end

  def set_vessel
    @vessel = @company.vessels.find(params[:id])
  end

  def vessel_params
    params.require(:vessel).permit(:name, :size_bbl)
  end
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/vessels/_form.html.haml
= form_with(model: @vessel, url: vessels_path(company_name: @company.slug), local: true) do |f|
  - if @vessel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vessel.errors.count, 'error')} prohibited this vessel from being saved:"
      %ul
        - @vessel.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', placeholder: 'Enter Vessel Name'

  .form-group
    = f.label :size_bbl, "Capacity (BBL)"
    = f.number_field :size_bbl, class: 'form-control', placeholder: 'Enter Capacity in BBLs'

  = f.submit 'Save Vessel', class: 'btn btn-primary'

app/views/vessels/edit.html.haml
%h2.text-primary.mb-4 Edit Vessel

= form_with(model: @vessel, url: vessel_path(company_name: @company.slug, id: @vessel), local: true, class: "card shadow-sm p-4") do |f|
  - if @vessel.errors.any?
    .alert.alert-danger
      %h4= "#{pluralize(@vessel.errors.count, 'error')} prevented this vessel from being saved:"
      %ul.mb-0
        - @vessel.errors.full_messages.each do |message|
          %li= message

  .row.g-3
    .col-md-6
      .form-group
        = f.label :name, "Vessel Name", class: 'form-label fw-bold'
        = f.text_field :name, class: 'form-control', placeholder: 'Enter Vessel Name'

    .col-md-6
      .form-group
        = f.label :size_bbl, "Capacity (BBL)", class: 'form-label fw-bold'
        = f.number_field :size_bbl, step: 0.1, class: 'form-control', placeholder: 'Enter Capacity in BBLs'

  .mt-4.d-flex.justify-content-end
    = f.submit 'Save Changes', class: 'btn btn-primary px-4'
    = link_to 'Cancel', vessels_path(company_name: @company.slug), class: 'btn btn-outline-secondary ms-2 px-4'

app/views/vessels/index.html.haml
.d-flex.justify-content-between.align-items-center.mb-3
  %h2.text-primary.mb-0 Vessels List
  = link_to new_vessel_path(company_name: @company.slug), class: "btn btn-outline-success d-flex align-items-center gap-2" do
    %i.fas.fa-plus-circle
    Add Vessel

/ Responsive Table Wrapper
.table-responsive
  %table.table.table-hover.table-striped.text-center
    %thead.thead-dark
      %tr
        %th Name
        %th Capacity (BBL)
        %th In Use
        %th Actions
    %tbody
      - if @vessels.any?
        - @vessels.each do |vessel|
          %tr
            %td= vessel.name
            %td= vessel.size_bbl
            %td
              - if vessel.brews.active.any?
                %span.badge.bg-success.text-white Yes
              - else
                %span.badge.bg-danger.text-white No
            %td.text-center
              .d-flex.justify-content-center.gap-2
                = link_to vessel_path(company_name: @company.slug, id: vessel), class: "btn btn-sm btn-light", title: "View Vessel" do
                  %i.fas.fa-eye
                = link_to edit_vessel_path(company_name: @company.slug, id: vessel), class: "btn btn-sm btn-light", title: "Edit Vessel" do
                  %i.fas.fa-edit
                = link_to vessel_path(company_name: @company.slug, id: vessel), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger", title: "Delete Vessel" do
                  %i.fas.fa-trash
      - else
        %tr
          %td.colspan-4.text-muted.text-center No vessels found.

app/views/vessels/new.html.haml
%h2.text-primary.mb-4 Add New Vessel

= form_with(model: @vessel, url: vessels_path(company_name: @company.slug), local: true, class: "card shadow-sm p-4") do |f|
  - if @vessel.errors.any?
    .alert.alert-danger
      %h4= "#{pluralize(@vessel.errors.count, 'error')} prevented this vessel from being saved:"
      %ul.mb-0
        - @vessel.errors.full_messages.each do |message|
          %li= message

  .row.g-3
    .col-md-6
      .form-group
        = f.label :name, "Vessel Name", class: 'form-label fw-bold'
        = f.text_field :name, class: 'form-control', placeholder: 'Enter Vessel Name'

    .col-md-6
      .form-group
        = f.label :size_bbl, "Capacity (BBL)", class: 'form-label fw-bold'
        = f.number_field :size_bbl, step: 0.1, class: 'form-control', placeholder: 'Enter Capacity in BBLs'

  .mt-4.d-flex.justify-content-end
    = f.submit 'Save Vessel', class: 'btn btn-primary px-4'
    = link_to 'Cancel', vessels_path(company_name: @company.slug), class: 'btn btn-outline-secondary ms-2 px-4'

app/views/vessels/show.html.haml
.card.shadow-sm.p-4
  .card-body
    %h2.text-primary.mb-3= "Vessel: #{@vessel.name}"

    .row.g-3
      .col-md-6
        %p.mb-1
          %strong Name:
          = @vessel.name
      .col-md-6
        %p.mb-1
          %strong Capacity (BBL):
          = @vessel.size_bbl

    .row.g-3.align-items-center
      .col-md-6
        %p.mb-1
          %strong In Use:
          - if @vessel.brews.active.any?
            %span.badge.bg-success.text-white.ms-2 Yes
          - else
            %span.badge.bg-danger.text-white.ms-2 No

    %hr/

    .d-flex.justify-content-end.mt-3
      = link_to edit_vessel_path(company_name: @company.slug, id: @vessel), class: 'btn btn-outline-secondary d-flex align-items-center gap-2' do
        %i.fas.fa-edit
        Edit Vessel
      = link_to vessels_path(company_name: @company.slug), class: 'btn btn-primary d-flex align-items-center gap-2 ms-2' do
        %i.fas.fa-arrow-left
        Back to Vessels