config/routes.rb
Rails.application.routes.draw do
  # Invitation routes
  # # resources :invitations, only: [:new, :create]
  # get 'accept_invitation', to: 'invitations#accept'
  # post 'complete_registration', to: 'invitations#complete_registration'
  # Root and authentication
  root to: 'home#welcome'

  # Scoped routes based on company name
  scope '/:company_name' do
    # Move set_password and update_password outside company scope

    # Invitation routes
    resources :invitations, only: [:new, :create]
    get 'accept_invitation', to: 'invitations#accept', as: 'accept_invitation'
    get 'dashboard', to: 'dashboards#show', as: :company_dashboard
    resources :companies
    # Keg inventory routes
    get 'keg_inventory', to: 'keg_inventory#index', as: :keg_inventory
    get 'keg_inventory/:recipe_id', to: 'keg_inventory#show', as: :keg_inventory_show
    post 'share_kegs', to: 'keg_inventory#share', as: :share_kegs
    resources :brews do
      member do
        post :empty_vessel
      end
      # Adding routes for viewing all logs and specific log actions
      post :transfer_kegs, on: :member
      resources :mash_logs, only: [:index, :new, :create, :edit, :update]
      resources :boil_logs, only: [:index, :new, :create, :edit, :update] do
        collection do
          get :new_preboil
          post :create_preboil
          get :new_postboil
          post :create_postboil
        end
      end
      resources :addition_logs, only: [:index, :new, :create, :edit, :update]
      resources :yeast_and_knockout_logs, only: [:index, :new, :create, :edit, :update]
      resources :fermentation_logs, only: [:index, :new, :create]
    end

    resources :recipes
    resources :vessels
    resources :ingredients
    resources :kegs
    post 'switch_company', to: 'companies#switch_company', as: :switch_company
  end

  # Company routes
  resources :companies
end

app/models/company.rb
class Company < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Relationships
  has_many :recipes
  has_many :vessels
  has_many :brews
  has_many :ingredients
  has_many :kegs
  has_many :keg_shares, dependent: :destroy
  has_many :shared_kegs, through: :keg_shares, source: :keg

  # Partnerships (self-referential many-to-many)
  has_many :partnerships, dependent: :destroy
  has_many :partners, through: :partnerships, source: :partner

  has_many :inverse_partnerships, class_name: 'Partnership', foreign_key: :partner_id, dependent: :destroy
  has_many :inverse_partners, through: :inverse_partnerships, source: :company

  # Combine direct and inverse partnerships
  def all_partners
    (partners + inverse_partners).uniq
  end

  # Friendly ID
  def should_generate_new_friendly_id?
    name_changed? || slug.blank?
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_available_partners, only: [:edit, :update, :new, :create]

  # GET /companies
  def index
    @companies = Company.all

    respond_to do |format|
      format.html  # This will render the Haml view
      format.json { render json: @companies }
    end
  end

  # GET /companies/:id
  def show
    @viewed_company = Company.find(params[:id])
    respond_to do |format|
      format.html  # This will render the Haml view
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        update_partnerships(@company, company_params[:partner_ids])
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /companies/:id/edit
  def edit
  end

  # PATCH/PUT /companies/:id
  def update
    respond_to do |format|
      if @company.update(company_params)
        update_partnerships(@company, company_params[:partner_ids])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render json: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/:id
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def switch_company
    company = Company.find(params[:company_id])
  
    # Ensure the user has access to switch to this company
    if current_user.company.partner_companies.include?(company.id) || current_user.admin? || current_user.manager?
      current_user.update!(company_id: company.id)
      flash[:notice] = "You have switched to #{company.name}."
    else
      flash[:alert] = "You are not authorized to switch to this company."
    end
  
    redirect_to company_dashboard_path(company_name: company.slug)
  end

  private

  def set_company
    @company = Company.find(params[:id]) if params[:id]
  end

  def set_available_partners
    @available_partners = Company.where.not(id: @company&.id)
  end

  def company_params
    params.require(:company).permit(:name, partner_ids: [])
  end

  # Handle partnerships
  def update_partnerships(company, partner_ids)
    return unless partner_ids

    partner_ids = partner_ids.reject(&:blank?).map(&:to_i)
    existing_partner_ids = company.partners.pluck(:id)

    # Add new partnerships
    (partner_ids - existing_partner_ids).each do |partner_id|
      company.partnerships.create!(partner_id: partner_id)
    end

    # Remove old partnerships
    (existing_partner_ids - partner_ids).each do |partner_id|
      partnership = company.partnerships.find_by(partner_id: partner_id)
      partnership.destroy if partnership
    end
  end

  def admin_only
    redirect_to root_path, alert: 'Access denied.' unless current_user.admin?
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.haml
%h2.mb-3.text-primary= action_name == 'new' ? 'New Company' : 'Edit Company'

/ **Company Edit Form**
.border.rounded.p-3.shadow-sm
  = form_for @company do |f|
    - if @company.errors.any?
      .alert.alert-danger
        %h4= "#{pluralize(@company.errors.count, 'error')} prohibited this company from being saved:"
        %ul.mb-0
          - @company.errors.full_messages.each do |message|
            %li= message

    .row.g-3
      .col-md-6
        .form-group
          = f.label :name, "Company Name", class: 'form-label fw-bold'
          = f.text_field :name, class: 'form-control', placeholder: "Enter company name"

      .col-md-6
        .form-group
          = f.label :partner_ids, "Partner Companies", class: 'form-label fw-bold'
          = f.collection_select :partner_ids, @available_partners, :id, :name, 
            { prompt: "Select Partner Companies" }, 
            { multiple: true, class: 'form-control', value: @company.partner_ids }

    / **Form Actions**
    .mt-4.d-flex.justify-content-end.gap-2
      = f.submit action_name == 'new' ? 'Create Company' : 'Update Company', class: 'btn btn-primary px-4'
      = link_to 'Back to Companies', companies_path, class: 'btn btn-outline-secondary px-4'

app/views/companies/index.html.haml
%h2.text-primary.mb-3 Companies
/ "New Company" button (Only for Admins/Managers)
- if current_user&.admin? || current_user&.manager?
  .d-flex.justify-content-end.mb-3
    = link_to new_company_path(company_name: current_user.company.slug), class: "btn btn-sm btn-success d-flex align-items-center gap-2" do
      %i.fas.fa-plus-circle
      %span.d-none.d-sm-inline Add Company

/ Companies List
.table-responsive
  %table.table.table-hover.table-striped.text-center
    %thead.thead-dark
      %tr
        %th Name
        %th Actions
    %tbody
      - @companies.each do |company|
        %tr
          %td= company.name
          %td
            .d-flex.justify-content-center.gap-2
              = link_to company_path(id: company.id, company_name: current_user.company.slug), class: "text-primary text-decoration-none" do
                %i.fas.fa-eye
              - if current_user&.admin? || current_user&.manager?
                = link_to edit_company_path(id: company.id, company_name: current_user.company.slug), class: "text-warning text-decoration-none" do
                  %i.fas.fa-edit
                = link_to company_path(id: company.id, company_name: current_user.company.slug), method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger text-decoration-none" do
                  %i.fas.fa-trash

app/views/companies/new.html.haml
%h2.text-primary.mb-3= action_name == 'new' ? 'New Company' : 'Edit Company'

.card.shadow-sm.p-4
  .card-body
    = form_with(model: @company, url: @company.persisted? ? company_path(@company) : companies_path, local: true) do |f|
      - if @company.errors.any?
        .alert.alert-danger
          %h4= "#{pluralize(@company.errors.count, 'error')} prohibited this company from being saved:"
          %ul.mb-0
            - @company.errors.full_messages.each do |message|
              %li= message

      .row.g-3
        .col-md-6
          .form-group
            = f.label :name, "Company Name", class: 'form-label fw-bold'
            = f.text_field :name, class: 'form-control', placeholder: 'Enter Company Name'

        .col-md-6
          .form-group
            = f.label :partner_ids, "Partner Companies", class: 'form-label fw-bold'
            = f.collection_select :partner_ids, @available_partners, :id, :name, { prompt: "Select Partner Companies" }, { multiple: true, class: 'form-control' }

      .mt-4.d-flex.justify-content-end.gap-3
        = link_to 'Cancel', companies_path, class: 'btn btn-outline-secondary px-4'
        = f.submit action_name == 'new' ? 'Create Company' : 'Update Company', class: 'btn btn-primary px-4'

app/views/companies/show.html.haml
%h2.text-primary.mb-3= @viewed_company.name

.row.g-4
  / **Company Details Section**
  .col-md-6
    .border.rounded.p-3.h-100
      %h5.text-primary.mb-3 Company Details
      %table.table.table-borderless.mb-0
        %tbody
          %tr
            %td.text-muted Name:
            %td= @viewed_company.name
          %tr
            %td.text-muted Created At:
            %td= @viewed_company.created_at.strftime("%B %d, %Y")
          %tr
            %td.text-muted Last Updated:
            %td= @viewed_company.updated_at.strftime("%B %d, %Y")

  / **Partner Companies Section**
  .col-md-6
    .border.rounded.p-3.h-100
      %h5.text-primary.mb-3 Partner Companies
      - if @viewed_company.partnerships.any?
        %ul.list-group
          - @viewed_company.partnerships.each do |partnership|
            %li.list-group-item
              = link_to partnership.partner.name, company_path(id: partnership.partner.id, company_name: current_user.company.slug), class: "text-decoration-none"
      - else
        %p.text-muted No partners assigned yet.

%hr/

/ **Users in Company Section**
%h5.text-primary.mb-3 Users in Company
.table-responsive
  %table.table.table-hover.table-striped.text-center
    %thead
      %tr
        %th Name
        %th Email
        %th Role
    %tbody
      - @viewed_company.users.each do |user|
        %tr
          %td= "#{user.first_name} #{user.last_name}"
          %td= user.email
          %td= user.role.titleize

%hr/

/ **Actions (Only Visible for Admins & Managers)**
- if current_user.admin? || current_user.manager?
  .d-flex.justify-content-end.gap-2
    = link_to edit_company_path(id: @viewed_company.id, company_name: current_user.company.slug), class: "btn btn-sm btn-outline-warning d-flex align-items-center gap-2" do
      %i.fas.fa-edit
      Edit
    = link_to company_path(id: @viewed_company.id, company_name: current_user.company.slug), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger d-flex align-items-center gap-2" do
      %i.fas.fa-trash
      Delete
    = link_to edit_company_path(id: @viewed_company.id, company_name: current_user.company.slug), class: "btn btn-sm btn-outline-secondary d-flex align-items-center gap-2" do
      %i.fas.fa-user-friends
      Add Partner

/ **Back Button**
.d-flex.justify-content-start.mt-3
  = link_to companies_path(company_name: current_user.company.slug), class: "text-secondary text-decoration-none d-flex align-items-center gap-2" do
    %i.fas.fa-arrow-left
    Back to Companies